### ISSUE TITLE
奇怪插件列表里显示不出来

### ISSUE THREAD

**Issue by kentzhu** [sbwtw/pidgin-wechat#11]
ElementaryOS 0.4
安装了pidgin和pidgin-dev
分别把libwechat.so复制到了
`~/.purple/plugins`
`/usr/lib/pidgin `
`/usr/lib/purple-2` 
插件管理器里都没有显示。。。不熟悉linux不知道什么情况。。谢谢。。

**Comment by sbwtw** [comment]
执行
`ldd libwechat.so`
看看是不是缺少库依赖，估计是由于依赖版本对不上了，可以尝试自行编译使用

**Comment by kentzhu** [comment]
这样啊，我试试看，谢谢～
