### ISSUE TITLE
非常看好这个项目

### ISSUE THREAD

**Issue by csbde** [sbwtw/pidgin-wechat#12]
在linux下面实用微信太痛苦了，如果能在pidfin里面使用真是福音。

但目前这个项目的可用性还不是很高，能否考虑实用wxbot项目的成果以加快功能开发和实现。

**Comment by sbwtw** [comment]
有在研究其它的实现，现在进度是卡在图片上传那里了，multipart 怎么也弄不对 😂😂😂

发自我的 iPad

**Comment by csbde** [comment]
感谢你的努力工作，我们才能看到在linux下使用微信的希望😬
