### ISSUE TITLE
请问这个插件怎么用啊

### ISSUE THREAD

**Issue by JadeVane** [sbwtw/pidgin-wechat#15]
- My system:
    > Debian & Gnome

- My pidgin version is:
    > Pidgin 2.12.0 (libpurple 2.12.0)

- My pidgin-wechat version is:
    > 0.11

- standard output:
    > none

- coredump file or debugger's stack trace:
    > 

pidgin也正常安装打开了，libwechat.so也复制到~/.purple/plugins了，但是协议下拉列表里面怎么找不到？还是说不是在这里启动？第一次用pidgin，恕我愚昧。

**Comment by sbwtw** [comment]
试试重新编译？可能你的 libppurple 与插件不兼容
