### ISSUE TITLE
收取消息崩溃

### ISSUE THREAD

**Issue by zhupengjia** [sbwtw/pidgin-wechat#5]
版本： 
90a4ae3d57ad50acb8d80d74735e4d8e098e92c0

收取链接的时候崩溃的。已上传shell信息和coredump:
[pidgin.zip](https://github.com/sbwtw/pidgin-wechat/files/999179/pidgin.zip)

shell output:
 {"AddMsgCount":1,"AddMsgList":[{"AppInfo":{"AppID":"","Type":0},"AppMsgType":0,"Content":"https://www.tensorflow.org/tutorials/","CreateTime":1494748763,"FileName":"","FileSize":"","ForwardFlag":0,"FromUserName":"@5e884122ab556215f061fd52a9399b4f","HasProductId":0,"ImgHeight":0,"ImgStatus":1,"ImgWidth":0,"MediaId":"","MsgId":"2352766951486417683","MsgType":1,"NewMsgId":2352766951486417683,"OriContent":"","PlayLength":0,"RecommendInfo":{"Alias":"","AttrStatus":0,"City":"","Content":"","NickName":"","OpCode":0,"Province":"","QQNum":0,"Scene":0,"Sex":0,"Signature":"","Ticket":"","UserName":"","VerifyFlag":0},"Status":3,"StatusNotifyCode":0,"StatusNotifyUserName":"","SubMsgType":0,"Ticket":"","ToUserName":"@@368a4bb9338b101d6b66c9e58aeba5e6754f90dd64a3e1bd870a637c24d94f2b","Url":"","VoiceLength":0}],"BaseResponse":{"ErrMsg":"","Ret":0},"ContinueFlag":0,"DelContactCount":0,"DelContactList":[],"ModChatRoomMemberCount":0,"ModChatRoomMemberList":[],"ModContactCount":0,"ModContactList":[],"Profile":{"Alias":"","BindEmail":{"Buff":""},"BindMobile":{"Buff":""},"BindUin":0,"BitFlag":0,"HeadImgUpdateFlag":0,"HeadImgUrl":"","NickName":{"Buff":""},"PersonalCard":0,"Sex":0,"Signature":"","Status":0,"UserName":{"Buff":""}},"SKey":"","SyncCheckKey":{"Count":10,"List":[{"Key":1,"Val":637490453},{"Key":2,"Val":637490530},{"Key":3,"Val":637490454},{"Key":11,"Val":637490465},{"Key":13,"Val":637470341},{"Key":201,"Val":1494748763},{"Key":203,"Val":1494733869},{"Key":1000,"Val":1494734761},{"Key":1001,"Val":1494734791},{"Key":1004,"Val":1494344568}]},"SyncKey":{"Count":10,"List":[{"Key":1,"Val":637490453},{"Key":2,"Val":637490530},{"Key":3,"Val":637490454},{"Key":11,"Val":637490465},{"Key":13,"Val":637470341},{"Key":201,"Val":1494748763},{"Key":203,"Val":1494733869},{"Key":1000,"Val":1494734761},{"Key":1001,"Val":1494734791},{"Key":1004,"Val":1494344568}]}}
purple_find_chat for token 0, result = 0x0
join chat "@@368a4bb9338b101d6b66c9e58aeba5e6754f90dd64a3e1bd870a637c24d94f2b", token = 0
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5

**Comment by sbwtw** [comment]
嗯，这是个 bug，现在初始化的时候没有获取所有的群列表，导致收到其它的群（token = 0）的时候会崩溃

**Comment by sbwtw** [comment]
简单解决了一下崩溃的问题，不过由于没有这个群的信息，目前会创建一个空的会话来保证消息能显示，之后重新获取并刷新群信息就可以了
